# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


def forwards_copy_student_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    StudentProfile = apps.get_model("accounts", "StudentProfile")

    used = set(
        User.objects.exclude(student_number__isnull=True)
        .exclude(student_number="")
        .values_list("student_number", flat=True)
    )

    for user in User.objects.all():
        value = None
        try:
            profile = StudentProfile.objects.get(user_id=user.id)
            value = profile.student_number
        except StudentProfile.DoesNotExist:
            value = user.username

        if not value:
            value = f"user-{user.id}"

        candidate = value
        suffix = 1
        while candidate in used:
            if suffix == 1:
                candidate = f"{value}-{user.id}"
            else:
                candidate = f"{value}-{suffix}"
            suffix += 1

        user.student_number = candidate
        user.save(update_fields=["student_number"])
        used.add(candidate)


def backwards_restore_profile_student_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    StudentProfile = apps.get_model("accounts", "StudentProfile")

    for user in User.objects.all():
        profile, _ = StudentProfile.objects.get_or_create(user_id=user.id)
        profile.student_number = user.student_number
        profile.save(update_fields=["student_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="student number"),
        ),
        migrations.RunPython(
            forwards_copy_student_numbers,
            backwards_restore_profile_student_numbers,
        ),
        migrations.AlterField(
            model_name="user",
            name="student_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="student number"),
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_number",
        ),
    ]
