# Generated by Django 6.0.1 on 2026-02-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_number_and_profile_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='curriculum',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dual_citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extension_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
