# Generated by Django 6.0.1 on 2026-02-10

from django.db import migrations, models


def forwards_copy_address(apps, schema_editor):
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    for p in StudentProfile.objects.all():
        if hasattr(p, "address_line"):
            p.current_address_line = p.address_line
        if hasattr(p, "country"):
            p.current_country = p.country
        if hasattr(p, "province"):
            p.current_province = p.province
        if hasattr(p, "city"):
            p.current_city = p.city
        if hasattr(p, "postal_code"):
            p.current_postal_code = p.postal_code
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentprofile_address_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="current_address_line",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="same_as_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="permanent_address_line",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="permanent_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="permanent_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="permanent_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="permanent_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="intake",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="learning_modality",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="advisor_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mentor_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="photo_file",
            field=models.FileField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="signature_file",
            field=models.FileField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.RunPython(forwards_copy_address, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="studentprofile",
            name="address_line",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="province",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="postal_code",
        ),
    ]
