# Generated by Django 6.0.1 on 2026-02-02 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('units', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Enlistment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (Pending Adviser)'), ('RETURNED', 'Returned for Revision'), ('FINANCE_REVIEW', 'Pending Admin/Finance Review'), ('FINANCE_HOLD_BALANCE', 'Hold (Unpaid Balance)'), ('FINANCE_HOLD_ACADEMIC', 'Hold (Academic Issue)'), ('FINANCE_APPROVED', 'Cleared by Admin/Finance'), ('APPROVED_FOR_PAYMENT', 'Approved for Payment'), ('ENROLLED', 'Enrollment Confirmed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser_final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_enlistments', to=settings.AUTH_USER_MODEL)),
                ('adviser_preapproved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preapproved_enlistments', to=settings.AUTH_USER_MODEL)),
                ('finance_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_checked_enlistments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlistments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enlistment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='enrollment.enlistment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTermSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('passed', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'ordering': ['-school_year', 'semester', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='EnlistmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlistment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_subjects', to='enrollment.enlistment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'unique_together': {('enlistment', 'subject')},
            },
        ),
    ]
