# Generated by Django 6.0.1 on 2026-02-04 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned for Revision'), ('PREAPPROVED', 'Adviser Pre-Approved'), ('FINANCE_REVIEWED', 'Finance Reviewed'), ('FINANCE_HELD', 'Finance Hold'), ('FINAL_APPROVED', 'Adviser Final Approved'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ENROLLED', 'Enrolled')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_actions', to=settings.AUTH_USER_MODEL)),
                ('enlistment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to='enrollment.enlistment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
