# Generated by Django 6.0.1 on 2026-02-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_historylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='historylog',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned for Revision'), ('PREAPPROVED', 'Adviser Pre-Approved'), ('FINANCE_REVIEWED', 'Finance Reviewed'), ('FINANCE_HELD', 'Finance Hold'), ('AMOUNT_SET', 'Amount Set'), ('FINAL_APPROVED', 'Adviser Final Approved'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ENROLLED', 'Enrolled')], max_length=50),
        ),
        migrations.AddField(
            model_name='enlistment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enlistments', to='enrollment.category'),
        ),
    ]
