# Generated by Django 6.0.1 on 2026-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_program_enlistment_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Window',
                'verbose_name_plural': 'Enrollment Window',
            },
        ),
    ]
