# Generated by Django 6.0.1 on 2026-02-10 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_enrollmentwindow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(blank=True, max_length=50)),
                ('total_classes', models.PositiveSmallIntegerField(default=0)),
                ('total_present', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'ordering': ['subject__code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumProgressCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, max_length=20)),
                ('curriculum_pattern', models.CharField(blank=True, max_length=50)),
                ('course_name', models.CharField(blank=True, max_length=150)),
                ('course_type', models.CharField(blank=True, max_length=50)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'semester_name', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumProgressSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, max_length=20)),
                ('earned_credits', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('registered_credits', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('remaining_credits', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sgpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semesters', models.PositiveSmallIntegerField(default=1)),
                ('deferment_type', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, max_length=20)),
                ('period_no', models.CharField(blank=True, max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='permits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=50)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='OverallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(blank=True, max_length=20)),
                ('total_subjects', models.PositiveSmallIntegerField(default=0)),
                ('gwa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-result_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OverallResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(blank=True, max_length=50)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('final_grade', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enrollment.overallresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'ordering': ['subject__code'],
            },
        ),
    ]
