# Generated by Django 6.0.1 on 2026-02-16 01:00

from django.db import migrations, models


def copy_existing_amount_to_tuition(apps, schema_editor):
    Payment = apps.get_model('enrollment', 'Payment')
    for payment in Payment.objects.all():
        payment.tuition_amount = payment.amount or 0
        ref = (payment.reference or "").upper()
        if "DOWNPAYMENT" in ref and (payment.submitted_amount or 0) > 0:
            payment.enlistment_amount = max(payment.enlistment_amount or 0, payment.submitted_amount or 0)
            payment.enlistment_paid_amount = payment.submitted_amount or 0
            payment.enlistment_paid = True
        payment.save(
            update_fields=[
                'tuition_amount',
                'enlistment_amount',
                'enlistment_paid_amount',
                'enlistment_paid',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_payment_submitted_amount_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enlistment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='enlistment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='enlistment_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuition_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuition_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(copy_existing_amount_to_tuition, migrations.RunPython.noop),
    ]
