# Generated by Django 5.0.10 on 2026-03-05 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_payment_enlistment_amount_payment_enlistment_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlistmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tuition_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enlistment_blocks', to=settings.AUTH_USER_MODEL)),
                ('enlistment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_options', to='enrollment.enlistment')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('enlistment', 'name')},
            },
        ),
        migrations.AddField(
            model_name='enlistment',
            name='selected_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_enlistments', to='enrollment.enlistmentblock'),
        ),
        migrations.CreateModel(
            name='EnlistmentBlockSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=120)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='enrollment.enlistmentblock')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
            ],
            options={
                'ordering': ['subject__code', 'schedule'],
                'unique_together': {('block', 'subject', 'schedule')},
            },
        ),
    ]
